name: Deploy to aws test

on:
  workflow_run:
    workflows: ["Label to docker develop"]
    types:
      - completed

jobs:
  deploy:
    #specify run on the self-host runner of github action
    runs-on: self-host
    steps:
      - name: Pull the docker image
        run: sudo docker pull jitao1102/prawn-api:latest
      - name: Remove old docker container
        run: sudo docker -rm prawn-api-container || True
      - name: Run docker container
        run: sudo docker run -d -p 28019:28019 --name prawn-api-container jitao1102/prawn-api

