#name: Deploy to aws test
#
#on:
#  workflow_run:
#    workflows: ["Label to docker develop"]
#    types:
#      - completed

name: Label to AWS Test
on:
  pull_request:
    types: [labeled]
    branch:
      - 'develop*'
jobs:
  cd-aws-test:
    # This will run only if the target branch matches "develop-1.0.0" pattern
    if: github.event.label.name == 'cd to aws test' && github.event.pull_request.merged == true
#    runs-on: ubuntu-latest
#
#jobs:
#  deploy:
#    #specify run on the self-host runner of github action
    runs-on: self-hosted
    steps:
      - name: Log messages
        run: echo "it is run"
#      - name: Pull the docker image
#        run: sudo docker pull jitao1102/prawn-api:latest
#      - name: Remove old docker container
#        run: sudo docker -rm prawn-api-container || True
#      - name: Run docker container
#        run: sudo docker run -d -p 28019:28019 --name prawn-api-container jitao1102/prawn-api

