name: Pull Request Merged to Develop
on:
  pull_request:
    branches: [ "develop" ]
    types: [closed]

jobs:
  run-on-merge:
    if: github.event.pull_request.merged == true  # Only run if the PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Run a script on merge
        run: echo "Pull request has been merged into the branch!"

      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: jitao1102/prawn-api
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

