name: Pull Request Merged to Develop
on:
  pull_request:
    types: [labeled]
env:
  IS_TARGET_BRANCH: ${{ startsWith(github.event.pull_request.base.ref, 'develop-') }}
  IS_VALID_LABEL: ${{ github.event.label.name == 'release to develop' }}

jobs:
  run-on-release-label:
    # This will run only if the target branch matches "develop-1.0.0" pattern
    if: |
      startsWith(github.event.pull_request.base.ref, 'develop-') &&
      github.event.label.name == 'release to develop'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: jitao1102/prawn-api
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

